rules:
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: true
  class-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  empty-line-between-blocks:
    - 2
    -
      include: true
      allow-single-line-rulesets: true
  extends-before-declarations: 2
  extends-before-mixins: 2
  final-newline: 2
  force-attribute-nesting: 0
  force-element-nesting: 2
  force-pseudo-nesting: 2
  function-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  hex-length: 0
  hex-notation:
    - 2
    -
      style: lowercase
  id-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  indentation: 2
  leading-zero: 0
  mixin-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  mixins-before-declarations:
    - 2
    -
      exclude: ['breakpoint', 'mq', 'media-breakpoint-up', 'media-breakpoint-down']
  nesting-depth:
    - 1 # only a warning
    -
      max-depth: 3
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    -
      allow-element-with-attribute: true
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 2
  no-transition-all: 1
  no-url-protocols: 1
  no-vendor-prefixes: 2
  no-warn: 2
  one-declaration-per-line: 2
  property-sort-order: 0
  quotes:
    - 2
    -
      style: single
  shorthand-values: 0
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-colon: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    -
      allow-leading-underscore: false
      convention: hyphenatedlowercase
  zero-unit: 2
